name = "build_runner"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
builder = { path = "../../builder" }
sara = { path = "../../sara" }
glance = ">= 6.0.0 and < 7.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
justin = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
