name = "builder"
version = "0.0.1"
description = "A code generation framework for Gleam"

licences = ["Apache-2.0"]
repository = { type = "github", user = "gungun974", repo = "Builder" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"
glexer = ">= 2.3.1 and < 3.0.0"
glance = ">= 6.0.0 and < 7.0.0"
tom = ">= 2.0.1 and < 3.0.0"
shellout = ">= 1.7.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
polly = ">= 3.0.0 and < 4.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
